version: "3.4"


services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: compose/celery/Dockerfile
    container_name: notebook 
    env_file:
      - ./envs/db_keys
    volumes:
      - ./src:/src
    depends_on:
      - db
    command : ["sh", "-c", "gunicorn quickstart.wsgi -b 0.0.0.0:8000"]

  db:
    image: postgres
    container_name: postgres_db
    env_file:
      - ./envs/db_keys
    volumes:
      - /psql_db/postgres_data:/var/lib/postgresql/data
      - /psql_db/postgres_data_backups:/backups

  adminer:
    image: adminer
    container_name: psql_admin
    ports:
      - "8080:8080"

  redis:
    image: redis:3.2-alpine
    container_name: cel_redis
    volumes:
      - ./redis_data:/data

  selenium-hub:
    image: selenium/hub:3.141.59-yttrium
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:3.141.59-yttrium
    container_name: chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    links:
      - "web:0.0.0.0"
      
  firefox:
    image: selenium/node-firefox:3.141.59-yttrium
    container_name: firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    links:
      - "web:0.0.0.0"
